### ISSUE TITLE
Running TGS in conda

### ISSUE THREAD

**Issue by desmodus1984** [BGI-Qingdao/TGS-GapCloser#20]
Hi,

I installed TGS in conda, and I was wondering if I still have to set the path to Racon and to Pilon because the environment where I will run TGS has them. Thus, I am unsure if I still have to set the path in python, or that in conda they will be automatically detected.

Second, I have access to cluster with 40 and 48 cores, should I increase the memory when using them, or the 300G will be sufficient?

Thanks;

**Comment by adonis316** [comment]
Hi,
The usage of TGS-GapCloser would be the same. You need to specify the installed path for racon or pilon, along with the short reads or long reads for error correction no matter how it was installed. For instance, you can use pilon by --pilon  …/pilon-1.23.jar” or racon by “--racon  …/anaconda2/bin/racon”.

The more clusters will definitely accelerate the speed of alignment and error correction. However, the memory limit is determined by the racon or pilon, and thus it depends on the size of genome as well as the input long-read data. Based on our experience, 300G is enough for a human-like genome with 10X coverage of long reads.

Thanks,	
Mengyang

**Comment by desmodus1984** [comment]
Hi,
I would like to know how to run in conda? I tried using the suggested command, I got an error. This didn't work 
TGS-GapCloser.sh
Also, in the cluster where I will run the test samtools is installed but I don't now the path. I basically load it, will the program detect it and init the commands? Also, It doesn't say anything about setting the path to it.

Finally, what coverage of the short reads for Pilon you suggest? I have tried MaSurca, which then creates SuperReads, which are supposed to contain all the short-reads (http://www.genome.umd.edu/):
```part of the MaSuRCA distribution, converts Illumina paired-end reads into super-reads. Super-reads satisfy the following properties:
Each of the original reads is contained in a super-read.
Many of the original reads yield the same super-read. Using super-reads leads to vastly reduced dataset.```
Can I use those or should I use the original short-reads?

Regards;

**Comment by adonis316** [comment]
Hi,
Could you provide more details about what command you are using and what error message you got? In conda, you should run "tgsgapcloser" instead of "TGS-GapCloser.sh". You can find the usage by running " tgsgapcloser --help".

The Pilon package is a java JAR file without the requirement of installation, and you can download it from https://github.com/broadinstitute/pilon/releases/download/v1.23/pilon-1.23.jar. The path where you download it should be "--pilon Download_Path"
.
You can run "which samtools" to detect the samtools path. TGS-Gapcloser will not automatically find the samtools unless you input the path.

The Pilon software uses the paired-end information to correct long reads. I would suggest to use the original paired-end short reads directly (>50x). I have not tried MaSurca SuperReads yet. 

Thanks,
Mengyang

**Comment by desmodus1984** [comment]
Hi, I am trying to update the package, and with the following code: conda install tgsgapcloser, 
I got the following error:
InvalidVersionSpecError: Invalid version spec: =2.7

**Comment by cchd0001** [comment]
Hi , could you please install TGSGapCloser by github ?   I am not familar with conda.
