### ISSUE TITLE
Error in Minimap2 path in conda in the main script (conda install)

### ISSUE THREAD

**Issue by agroppi** [BGI-Qingdao/TGS-GapCloser#25]
There is a small error in the main script after an install with conda
`/intall_dir/bin/tgsgapcloser`

I uncommented and changed line #279
`#MiniMap2=$HOOM_DIR"/tgsgapcloserbin/minimap2"`
to
`MiniMap2=$HOOM_DIR"/minimap2"`

and I commented the line #280
`#MiniMap2=minimap2`

**Comment by cchd0001** [comment]
Hi Dr. Groppi,
Thank you for pointing out this important dependence.
 
Initially, we would like to wrap minimap2 as a third-part module and submit it to conda to avoid an additional installation. However, it was not allowed by conda since minimap2 had already been shipped. Therefore, we assumed users might have minimap2 in conda environment.
 
To clarify it, we have added a new instruction to the README file. Thank you for your comments.
 
Thanks,
Lidong Guo
