### ISSUE TITLE
TGS_GapCloser get killed in step 2.1 and step 4.1

### ISSUE THREAD

**Issue by jtndr011** [BGI-Qingdao/TGS-GapCloser#55]
Hi,

I am trying to fill the gaps with nano pore reads in our scaffolds using TGS_GapCloser, but from the past couple of days, it gets killed at Step 2.1. I tried both conda installation and git clone and make. But I am getting the same error.

I will really appreciate your help.

Here's the log file from TGS_GapCloser
```
INFO  :   Run TGS-GapCloser from . ;
          Version : 1.2.0 ;
          Release time : 2022-03-15 .


INFO  :   Parsing args starting ...
             --thread 24
             --scaff ./scaffold.fasta
             --reads ./ont_reads.fasta
             --output ./tgs_gapclosed
             --racon  /home/user/racon/build/bin/racon

INFO  :   Parsing args end .

INFO  :   Checking basic args & env ...
              -   Doing error correction by racon with tgs reads.
              -   TGS reads type is ont . MINIMAP2_PARAM is  -x ava-ont   MIN_IDY is 0.3 . MIN_MATCH is 300 .

INFO  :   Checking basic args & env end.

INFO  :   Step 1 , run TGSSeqSplit to split scaffolds into scaftigs(contigs). 
skip step1 since done_step1_tag exists

INFO  :   Step 1 , done .

INFO  :   Step 2 , run TGSCandidate ... 
              -   2.1 , run minmap2 to map contigs against tgs reads.
./TGS-GapCloser.sh: line 442: 1569445 Killed                  $MiniMap2 $MINIMAP2_PARAM -t $THREAD $TGS_READS $TMP_INPUT_SCAFTIG > $OUT_PREFIX.sub.paf 2> $OUT_PREFIX.minimap2.01.log
```

minimap2 log error [tgs_gapclosed.minimap2.01.log file]
```
[M::mm_idx_gen::232.430*2.01] collected minimizers
[M::mm_idx_gen::318.234*4.95] sorted minimizers
[M::main::318.236*4.95] loaded/built the index for 74494 target sequence(s)
[M::mm_mapopt_update::335.837*4.75] mid_occ = 1493
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 74494
[M::mm_idx_stat::347.457*4.62] distinct minimizers: 158915949 (45.38% are singletons); average occurrences: 5.282; average spacing: 2.936
```
Without racon (using --ne) 

```
INFO  :   Run TGS-GapCloser from . ;
          Version : 1.2.0 ;
          Release time : 2022-03-15 .


INFO  :   Parsing args starting ...
             --thread 24
             --scaff ./scaffold.fasta
             --reads ./ont_reads.fasta
             --output ./tgs_gapclosed
             --ne

INFO  :   Parsing args end .

INFO  :   Checking basic args & env ...
              -   Will not do error-correcting by --ne option
              -   TGS reads type is ont . MINIMAP2_PARAM is  -x ava-ont   MIN_IDY is 0.3 . MIN_MATCH is 300 .

INFO  :   Checking basic args & env end.

INFO  :   Step 1 , run TGSSeqSplit to split scaffolds into contigs. 

INFO  :   Step 1 , done .

INFO  :   Step 2 , skip TGSCandidate by --ne option.

INFO  :   Step 3 , skip error-correction by --ne option.

INFO  :   Step 4 , gap filling ... 
              -   Use ../ont_cut_20kb/ont_cutoff_20kb.fasta as final TGS READS input.
              -   4,1 , mapping contig into reads ... 
/home/user/miniconda3/bin/tgsgapcloser: line 517: 1563673 Killed                  $MiniMap2 $MINIMAP2_PARAM -t $THREAD $FINAL_READS $TMP_INPUT_SCAFTIG > $OUT_PREFIX.fill.paf 2> $OUT_PREFIX.minimap2.04.log
```
tgs_gapclosed.minimap2.04.log file
```
[M::mm_idx_gen::745.214*1.64] collected minimizers
[M::mm_idx_gen::864.960*3.45] sorted minimizers
[M::main::864.962*3.45] loaded/built the index for 1280251 target sequence(s)
[M::mm_mapopt_update::900.192*3.35] mid_occ = 1735
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1280251
[M::mm_idx_stat::919.897*3.30] distinct minimizers: 200302752 (38.00% are singletons); average occurrences: 6.773; average spacing: 2.949; total length: 4000495167
```

**Comment by cchd0001** [comment]
Hi,

This is the memory issue, please check issues #42 and #43 for details.

In brief: 

1. try reducing the coverage of reads if your reads coverage is too high ( greater than 50X ).
2. try modifying the minimap2 command like reducing -t thread_number and the -K query_base until it fits your RAM size.

**Comment by cchd0001** [comment]
Hi,

Yes,  your test is correct. Using reads as a reference to run minimap2 may trigger this huge memory issue.

As I mentioned, if the coverage of your input reads is high, please try to subsample it.


Or try ```minimap2 -t 12 -K 80M -x ava-ont ont_reads.fasta scaffold.fasta > ./minimap2_output/scaffold_mapping_on_ont.paf```, if it works, then edit the ```TGS-GapCloser.sh```  to add ``` -t 12 -K 80M```  into the minimap2 command.

Best wishes
Lidong Guo

**Comment by jtndr011** [comment]
Hi,

Our ONT coverage is only 3.5x. We generated this data to just fill the gaps in PacBio assembly (and we don't have many gaps). But, the genome size is about 4.35 Gb. 

I'll try the suggested command and see if that works.

Thank you.

**Comment by jtndr011** [comment]
Hi,

It also failed when I ran above code. Can you please suggest a way to use TGS_GapCloser on my university cluster, as they use PBS job script. I can access more resources there to make it work.

Thank you so much.

**Comment by cchd0001** [comment]
Please write a bash script and submit it.

For example :

edit run.sh like
```
#!/bin/bash

../TGS-GapCloser.sh --thread 24 --scaff input.scaff.fasta --reads ont.reads.fasta --output test_racon --racon /home/user/racon/build/bin/racon
```

then submit this script like any other command that you used before.


A dataset like yours may consume greater than 10G but less than 100G memory.

**Comment by jtndr011** [comment]
Hi,

Thank you. The script works.

Using ONT reads, it closed about 296 gaps. Then I separately, ran the minimap2 to map the ONT reads back to tags_gapclosed_assembly. I couldn't find any read mapped to gap positions at multiple instances. (I used the updated coordinates).

I attached the IGV screenshot and information from tgs_gapclosed.gap_fill_detail file. The TGS_gapcloser fill the gap with 225bp sequences. But when I map the raw ONT reads back to tgs_gapclosed.scaff_seqs.fasta file with minimap2, no read was mapped to that region as seen in the attached picture. The program was run without any error correction.

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/77622853/210676312-97c15044-8395-4fe1-869b-584f327ca8dd.png">

This happened multiple times. I also run TGS_Gapcloser with HiFi_reads with racon error correction step and same thing has been observed in that case.

What could be the possible reasons for this?

**Comment by cchd0001** [comment]
Hi,

Thanks for using our tool.

Basically, this issue might happen because of the high sequencing error rate of long reads. Mapping tools such as minimap2 might miss some true mappings (False Negative) or introduce incorrect mappings (False Positive) by the default parameters.

To increase the possibility of mapping, we used the contig-map-to-read strategy (long reads as reference, contigs as query). However, the mapping result is not the same as that of the read-map-to-contig strategy (contigs as reference, long reads as query). This is one of the reasons why the alignment cannot be found although this gap has been filled by TGS-GapCloser in your case.

These filling results might be not solid. It is great to manually check them by aligning the long reads back to the closed gap regions. I recommend doubling these filling results in the last manual curation step. Minimap2 with more strict parameters or BLAST can be applied if you would like to get highly confident gap-closing results.

Best wishes

**Comment by jtndr011** [comment]
Hi,

Thanks for the suggestions.

I aligned the long reads back to closed gap as you suggested by mapping contigs to reads. How can I visualize them? Is there any tool for that?

What do you mean by doubling the filling results, how can I do that?

Is TGS_GapCloser provide the information about the reads (read name id) that it used to close the gaps? 

I also used blast. I make the database of all ont reads and extract the 2kb region from both sides of closed gap. Then blast them. Is this the right approach?

Thank you.

**Comment by adonis316** [comment]
Hi,
IGV could be a great visualization tool to check the alignments.

“doubling the filling results” means “manually double-check the filling result by investigating the alignment of long reads against assembly sequences”. Sorry for the typos.

The current version of TGS_GapCloser does not provide read ids since the sequences used to fill the gap have been truncated and error-corrected. It is not easy to directly track which read it originates from. But the mapping relation can be easily obtained from the all-vs-all alignment. The intermediate paf file can also provide this information. But for the manual check, it is unnecessary to know the mapping relation or extract a subset of long reads.

I would recommend directly aligning all raw reads back to the gap-closed result (assembly generated by TGS_GapCloser) by blast or other mapping tools. You should look at the suspicious regions where only few reads can be mapped to the final sequence (which means how many reads support the gap-closing relationship). Otherwise, the gap-closing results that are supported by a number of mapping long reads (you can determine the threshold based on the sequencing depth but also consider the special regions) are reliable. 

Thanks,
Mengyang

**Comment by domewq** [comment]
你好

**Comment by domewq** [comment]
NFO  :   Parsing args starting ...
             --scaff ragtag.fasta
             --reads GT1_aln.fasta
          --minmap_arg -x asm20
             --racon  /data/home/wangqiang/miniconda3/bin/racon
             --tgstype pb
             --output GAP_fill

INFO  :   Parsing args end .

INFO  :   Checking basic args & env ...
              -   Doing error correction by racon with tgs reads.
              -   TGS reads type is pb . MINIMAP2_PARAM is -x asm20  MIN_IDY is 0.2 . MIN_MATCH is 200 .

INFO  :   Checking basic args & env end.

INFO  :   Step 1 , run TGSSeqSplit to split scaffolds into scaftigs(contigs). 
skip step1 since done_step1_tag exists

INFO  :   Step 1 , done .

INFO  :   Step 2 , run TGSCandidate ... 
skip step2.1 since done_step2.1_tag exists
skip step2.2 since done_step2.2_tag exists
skip step2.3 since done_step2.3_tag exists

INFO  :   Step 2 , done .

INFO  :   Step 3.A , error correction by racon ...  
              -   3.A.1 , racon each chunk ...  
              -      -   iteration 0 start ... 
              -      -   iteration 0 chunk 0 -  minimap2 indexing ... 
              -      -   iteration 0 chunk 0 -  minimap2 ... 
              -      -   iteration 0 chunk 0 -  racon ... 
你好，目前我的racon，到这一步就中断拉

**Comment by cchd0001** [comment]
Could you please provide the content of GAP_fill.curr_tag.racon.log for us?

**Comment by cchd0001** [comment]
Could you please provide the first 10 line of GAP_fill.ont.0.0.fasta? Racon detect no sequences data in this file, however this file is only a chunk of you input TGS reads.

**Comment by domewq** [comment]
GAP_fill.ont.0.0.fasta,This file is empty and does not generate data
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
Could you please provide the first 10 line of GAP_fill.ont.0.0.fasta? Racon detect no sequences data in this file, however this file is only a chunk of you input TGS reads.

**Comment by domewq** [comment]
The first time I used this software, it worked fine. Then use it again and you will encounter this problem, and the input file will also try to change, still encounter the same problem. It seems that the output after mapping is not generated


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
Could you please provide the first 10 line of GAP_fill.ont.0.0.fasta? Racon detect no sequences data in this file, however this file is only a chunk of you input TGS reads.

**Comment by cchd0001** [comment]
The paf file is empty?

**Comment by domewq** [comment]
The paf file is empty，yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 上午8:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
The paf file is empty?

**Comment by cchd0001** [comment]
It looks more like an input data issue rather than the software issue, please double check your input data,

**Comment by domewq** [comment]
The input data is all in fasta format, and the first time the software ran normally, then I changed the input scaff file, and there was such an error, but I changed back to the original file with the same error. The read files are all the same




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月9日(星期四) 上午9:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
It looks more like an input data issue rather than the software issue, please double check your input data,

**Comment by domewq** [comment]
The input data is all in fasta format, and the first time the software ran normally, then I changed the input scaff file, and there was such an error, but I changed back to the original file with the same error. The read files are all the same


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
It looks more like an input data issue rather than the software issue, please double check your input data,

**Comment by cchd0001** [comment]
TGSGapCloser support re-run by skipping finished steps.  If you change your input, please rerun it in an new clean folder.

**Comment by domewq** [comment]
Thanks, is the problem with my input file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 中午11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
TGSGapCloser support re-run by skipping finished steps.  If you change your input, please rerun it in an new clean folder.

**Comment by domewq** [comment]
Hello, last time you said the input file problem, how to adjust to the correct input file? My input files are all in fasta format.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 上午8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
Closed #55 as completed.

**Comment by cchd0001** [comment]
Fastq is the valid format for TGS-GapCloser. Could you please provide more details about your current issue?

**Comment by domewq** [comment]
Hello, is fastq okay? My input file is fasta, here are my related commands.
tgsgapcloser \
&nbsp; &nbsp; &nbsp; &nbsp; --scaff /data/home/wangqiang/GT1/500/MIT4_2.fasta \
&nbsp; &nbsp; &nbsp; &nbsp; --reads GT1_aln.fasta \
&nbsp; &nbsp; &nbsp; &nbsp; --tgstype pb \
&nbsp; &nbsp; &nbsp; &nbsp; --output gap_fill \
&nbsp; &nbsp; &nbsp; &nbsp; --minmap_arg '-x asm20' \
&nbsp; &nbsp; &nbsp; &nbsp; --racon /data/home/wangqiang/miniconda3/envs/DNA/bin/racon
&nbsp; &nbsp; &nbsp; &nbsp; &gt;pipe.log 2&gt;pipe.err







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 上午8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
Fastq is the valid format for TGS-GapCloser. Could you please provide more details about your current issue?

**Comment by cchd0001** [comment]
please provide the details of pipe.err

**Comment by domewq** [comment]
INFO&nbsp; :&nbsp; &nbsp;Parsing args end .


INFO&nbsp; :&nbsp; &nbsp;Checking basic args &amp; env ...
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;Doing error correction by racon with tgs reads.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;TGS reads type is pb . MINIMAP2_PARAM is -x asm20&nbsp; MIN_IDY is 0.2 . MIN_MATCH is 200 .


INFO&nbsp; :&nbsp; &nbsp;Checking basic args &amp; env end.


INFO&nbsp; :&nbsp; &nbsp;Step 1 , run TGSSeqSplit to split scaffolds into scaftigs(contigs).&nbsp;


INFO&nbsp; :&nbsp; &nbsp;Step 1 , done .


INFO&nbsp; :&nbsp; &nbsp;Step 2 , run TGSCandidate ...&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;2.1 , run minmap2 to map contigs against tgs reads.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;2.2 , run TGSGapCandidate to choose candidate seqs.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;2.3 , break candidates into 3 chunk(s).


INFO&nbsp; :&nbsp; &nbsp;Step 2 , done .


INFO&nbsp; :&nbsp; &nbsp;Step 3.A , error correction by racon ...&nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;3.A.1 , racon each chunk ...&nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;iteration 0 start ...&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;iteration 0 chunk 0 -&nbsp; minimap2 indexing ...&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;iteration 0 chunk 0 -&nbsp; minimap2 ...&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -&nbsp; &nbsp; &nbsp; -&nbsp; &nbsp;iteration 0 chunk 0 -&nbsp; racon ...&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月21日(星期二) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)






请提供pipe.err的详细信息

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by cchd0001** [comment]
Maybe this is a Racon issue rather than TGS-GapCloser issue. For example Older or Newer Racon version.

Please test the Racon command independently and dig out the real problem.

**Comment by domewq** [comment]
RACON has no problem and can bring up commands




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月21日(星期二) 中午1:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)






也许这是一个Racon的问题，而不是TGS-GapCloser的问题。例如旧的或新的Racon版本。

请独立测试Racon命令，找出真正的问题所在。

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by domewq** [comment]
[racon::Polisher::initialize] error: empty target sequences set!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 中午1:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] TGS_GapCloser get killed in step 2.1 and step 4.1 (Issue #55)





 
Maybe this is a Racon issue rather than TGS-GapCloser issue. For example Older or Newer Racon version.
 
Please test the Racon command independently and dig out the real problem.
